# Generated by Django 4.2.2 on 2023-06-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("author_name", models.CharField(max_length=20)),
                ("content", models.CharField(max_length=500)),
                ("image", models.ImageField(default="", upload_to="blogs/images")),
                ("likes_count", models.IntegerField(default=0)),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                ("last_edit_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("like", models.BooleanField(default=False)),
                ("comment", models.CharField(blank=True, max_length=100)),
                ("first_response_date", models.DateTimeField(auto_now_add=True)),
                ("last_response_edit_date", models.DateTimeField(auto_now=True)),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogs.posts"
                    ),
                ),
            ],
        ),
    ]
