# Generated by Django 4.2.2 on 2023-06-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentsresponse",
            name="reaction",
            field=models.CharField(default="", max_length=8),
        ),
    ]
