# Generated by Django 4.2.2 on 2023-06-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="likes_count",
        ),
    ]
