# Generated by Django 4.2.2 on 2023-06-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_commentsresponse_reaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentsresponse",
            name="response_flag",
        ),
    ]
