# Generated by Django 4.2.2 on 2023-06-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_posts_author_name_alter_response_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="likes_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="posts",
            name="author_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="response",
            name="username",
            field=models.CharField(max_length=20),
        ),
    ]
