# Generated by Django 4.2.2 on 2023-06-20 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_bloggallery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloggallery",
            name="blog",
        ),
        migrations.AddField(
            model_name="bloggallery",
            name="posts",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="blogs.posts",
            ),
        ),
    ]
