# Generated by Django 4.2.2 on 2023-06-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_posts_likes_count_alter_posts_author_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="likes_count",
        ),
    ]
