# Generated by Django 4.2.2 on 2023-06-20 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_remove_bloggallery_blog_bloggallery_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloggallery",
            name="images",
            field=models.ImageField(upload_to="blogs/gallery"),
        ),
        migrations.AlterField(
            model_name="commentsresponse",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blogs.response"
            ),
        ),
    ]
