# Generated by Django 4.2.2 on 2023-06-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_alter_response_post_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="nested",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="response",
            name="nested_response_id",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
    ]
