# Generated by Django 4.2.2 on 2023-06-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_subscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="last_update_date",
            new_name="last_logged_in",
        ),
    ]
