# Generated by Django 4.2.2 on 2023-06-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_response_nested_response_nested_response_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="comment",
            field=models.BooleanField(default=False),
        ),
    ]
