# Generated by Django 4.2.2 on 2023-06-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0008_rename_last_update_date_subscription_last_logged_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="accessed_blog_one",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="accessed_blog_two",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
