# Generated by Django 4.2.2 on 2023-06-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0008_alter_response_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="comment_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="response",
            name="comment",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
