# Generated by Django 4.2.2 on 2023-06-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0012_alter_subscription_accessed_blog_one_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="Subscription_purchase_date",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
