# Generated by Django 4.2.2 on 2023-06-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0014_blogstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogstats",
            name="image_like",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
