# Generated by Django 4.2.2 on 2023-06-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0015_alter_blogstats_image_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogstats",
            old_name="image_like",
            new_name="image_response",
        ),
    ]
